
INSERT INTO RNR_USUARIO (ID, NOME, LOGIN, SENHA, EMAIL,SITUACAO) VALUES (1, 'Rafael', 'rafael', '1234', 'rrafael.net@gmail.com', 'ATIVO');	

ALTER SEQUENCE RNR_USUARIO_ID_SEQ RESTART WITH 2;

INSERT INTO RNR_PERFIL (ID, DESCRICAO) VALUES (1, 'Administrador');
INSERT INTO RNR_PERFIL (ID, DESCRICAO) VALUES (2, 'Gerente');
INSERT INTO RNR_PERFIL (ID, DESCRICAO) VALUES (3, 'Cliente');

ALTER SEQUENCE RNR_PERFIL_ID_SEQ RESTART WITH 4;

INSERT INTO RNR_RECURSO (ID, NOME, CHAVE) VALUES (1, 'Tela Usuário', 'usuario');
INSERT INTO RNR_RECURSO (ID, NOME, CHAVE) VALUES (2, 'Tela Perfil', 'perfil');
INSERT INTO RNR_RECURSO (ID, NOME, CHAVE) VALUES (3, 'Tela Recurso', 'recurso');

ALTER SEQUENCE RNR_RECURSO_SEQ RESTART WITH 4;